name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-deps:
        name: Setup Dependencies
        runs-on: ubuntu-22.04

        steps:
          - uses: actions/checkout@v4
          - name: RUn
