name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-deps:
        name: Setup Dependencies
        runs-on: ubuntu-22.04

        steps:
          - name: Build Essentials Setup
            run: apt update && apt install build-essentials make -y
          - name: Checkout lowdown repo
            uses: actions/checkout@v4
            with:
              repository: kristapsdz/lowdown
          - name: Configure, Build and Install lowdown
            run: |
              cd lowdown
              ./configure
              make install
              make install_libs
