name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-deps:
        name: Setup Dependencies
        runs-on: ubuntu-22.04

        steps:
          - name: Checkout lowdown repo
            uses: actions/checkout@v4
            with:
              repository: fmash16/ssg5
          - name: Install Pandoc
            run: |
              sudo apt update
              sudo apt install -y texlive wget curl
              wget https://github.com/jgm/pandoc/releases/download/3.1.13/pandoc-3.1.13-1-amd64.deb
              sudo dpkg -i pandoc-3.1.13-1-amd64.deb
              pandoc --help
