name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-deps:
        name: Setup Dependencies
        runs-on: ubuntu-22.04

        steps:
          - name: Build Essentials Setup
            run: sudo apt update && sudo apt install build-essential make -y
          - name: Checkout lowdown repo
            uses: actions/checkout@v4
            with:
              repository: kristapsdz/lowdown
          - name: Configure, Build and Install lowdown
            run: |
              ./configure
              sudo make install
              sudo make install_libs
              lowdown --help
